### ISSUE TITLE
[BUG] There is ArgumentException during compilation in version 0.9.30

### ISSUE THREAD

**Issue by xandraele** [pamidur/aspect-injector#13]
Error	202	ArgumentException: Member 'System.Exception' is declared in another module and needs to be imported
   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   at Mono.Cecil.SignatureWriter.WriteTypeSignature(TypeReference type)
   at Mono.Cecil.SignatureWriter.WriteMethodSignature(IMethodSignature method)
   at Mono.Cecil.MetadataBuilder.GetMemberRefSignature(MemberReference member)
   at Mono.Cecil.MetadataBuilder.CreateMemberRefRow(MemberReference member)
   at Mono.Cecil.MetadataBuilder.GetMemberRefToken(MemberReference member)
   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
   at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypeDefs()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.ModuleWriter.<BuildMetadata>b__0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at AspectInjector.BuildTask.AspectInjectorBuildTask.Execute()
	OR.Data.Core

**Comment by pamidur** [comment]
Could you provide a sample code please?

**Comment by pamidur** [comment]
Btw, I am glad you keep trying using Aspect Injector, we were lack of new projects that could reveal existing problems. Thank you!

**Comment by xandraele** [comment]
Actually I don't know where exactly the exception occurs. It gives me the name of project only. Anyway that exception rises in all project where I use Aspect attribute. Version 0.9.2 is more stable for now.

**Comment by pamidur** [comment]
Do you have a System.Exception as a method parameter elsewhere?

**Comment by pamidur** [comment]
Hope it fixed in https://github.com/pamidur/aspect-injector/releases/tag/0.9.31
Could you check it out please?

**Comment by xandraele** [comment]
Fixed. Great work. Now it seems as the most stable version. Thanks a lot.

**Comment by pamidur** [comment]
Thank you for all those reports

**Comment by pamidur** [comment]
Reported fixed in https://github.com/pamidur/aspect-injector/releases/tag/0.9.31
