### ISSUE TITLE
AspectInjector|2.4.2 : error AI_ERR0: Processing failure: System.IO.IOException: The process cannot access the file *.pdb' because it is being used by another process.

### ISSUE THREAD

**Issue by matt-cochran** [pamidur/aspect-injector#141]
I have a solution with over 80 projects and am finding file io contention during the build in github on umbuntu (latest).  It works fine when I build locally in windows both through Visual studio and the `dotnet build` command.

**Comment by matt-cochran** [comment]
callstack: 

at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
     at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
     at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
     at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
     at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
     at FluentIL.PatcherBase.ReadAssembly(String assemblyFile, IAssemblyResolver resolver, Boolean readSymbols, Boolean verbose)
     at FluentIL.PatcherBase.Process(String assemblyFile, IAssemblyResolver resolver, Boolean optimize, Boolean verbose)
     at FluentIL.PatcherBase.Process(String assemblyFile, IReadOnlyList`1 references, Boolean optimize, Boolean verbose)
     at AspectInjector.Compiler.Execute(String filename, IReadOnlyList`1 references, Boolean optimize, Boolean verbose). Please submit an issue to https://github.com/pamidur/aspect-injector
  AspectInjector|2.4.2: Found 1 aspects, 0 injections

**Comment by pamidur** [comment]
Hi @matt-cochran , thanks for your report and PR! 
Do you use any other tool except AspectInjector? The reason I'm asking is that AI plugs itself the following way:
```xml
<Target Name="InjectAspects" AfterTargets="CoreCompile"/>
```
Thus it might happen than some other tool does the same and tries to access same pdb file in parallel

**Comment by pamidur** [comment]
@matt-cochran , Could you also check if v2.4.4-pre1 makes any difference?
