### ISSUE TITLE
Unsupported language/version ?

### ISSUE THREAD

**Issue by manson** [pamidur/aspect-injector#214]
**Environment:**
 - OS: windows10
 - Framework: 4.6.2
 - Type of application: asp.net,  class library
 - Version of AspectInjector: 2.8.1, 2.8.2-pre

I have an AP.NET big application with multiple sub projects (libraries). I have implemented a separate library Tracing with all aspects and attributes implementation. Next I have added reference to this project from main app and started testing, It worked well until I have finished the needed logic and applied attributes to all the classes I need to intercept behavior with AspectInjector. And after spending the whole day doing this, I got next error on building my app.

7>AspectInjector|2.8.1 : error AI_ERR0: Processing failure: System.InvalidOperationException: Expected sequence is not found even once. Unsupported language/version ?
7>     at FluentIL.MethodEditor.OnEveryOccasionOf(MethodBody body, Func`2 predicate, PointCut pc, Instruction startingFrom)
7>     at FluentIL.MethodEditor.OnCall(MethodBody body, MethodReference method, PointCut pc, Instruction startingFrom)
7>     at AspectInjector.Core.Advice.Weavers.Processes.AfterAsyncWeaveProcess.FindOrCreateAfterStateMachineMethod()
7>     at AspectInjector.Core.Advice.Weavers.Processes.AfterStateMachineWeaveProcessBase.Execute()
7>     at AspectInjector.Core.Advice.Weavers.AdviceStateMachineWeaver.WeaveMethod(MethodDefinition method, InjectionDefinition injection)
7>     at AspectInjector.Core.Advice.Weavers.AdviceInlineWeaver.Weave(InjectionDefinition injection)
7>     at AspectInjector.Core.Processor.PatchAssembly(AssemblyDefinition assembly, Boolean optimize, Boolean verbose)
7>     at FluentIL.PatcherBase.Process(String assemblyFile, IAssemblyResolver resolver, Boolean optimize, Boolean verbose)
7>     at FluentIL.PatcherBase.Process(String assemblyFile, IReadOnlyList`1 references, Boolean optimize, Boolean verbose)
7>     at AspectInjector.Compiler.Execute(String filename, IReadOnlyList`1 references, Boolean optimize, Boolean verbose). Please submit an issue to https://github.com/pamidur/aspect-injector
7>AspectInjector : error AI_FAIL: Aspect Injector processing has failed. See other errors.

The same for 2.8.2

7>AspectInjector|2.8.2 : error AI_ERR0: Processing failure: System.InvalidOperationException: Expected sequence is not found even once. Unsupported language/version ?
7>     at FluentIL.MethodEditor.OnEveryOccasionOf(MethodBody body, Func`2 predicate, PointCut pc, Instruction startingFrom)
7>     at FluentIL.MethodEditor.OnCall(MethodBody body, MethodReference method, PointCut pc, Instruction startingFrom)
7>     at AspectInjector.Core.Advice.Weavers.Processes.AfterAsyncWeaveProcess.FindOrCreateAfterStateMachineMethod()
7>     at AspectInjector.Core.Advice.Weavers.Processes.AfterStateMachineWeaveProcessBase.Execute()
7>     at AspectInjector.Core.Advice.Weavers.AdviceStateMachineWeaver.WeaveMethod(MethodDefinition method, InjectionDefinition injection)
7>     at AspectInjector.Core.Advice.Weavers.AdviceInlineWeaver.Weave(InjectionDefinition injection)
7>     at AspectInjector.Core.Processor.PatchAssembly(AssemblyDefinition assembly, Boolean optimize, Boolean verbose)
7>     at FluentIL.PatcherBase.Process(String assemblyFile, IAssemblyResolver resolver, Boolean optimize, Boolean verbose)
7>     at FluentIL.PatcherBase.Process(String assemblyFile, IReadOnlyList`1 references, Boolean optimize, Boolean verbose)
7>     at AspectInjector.Compiler.Execute(String filename, IReadOnlyList`1 references, Boolean optimize, Boolean verbose). Please submit an issue to https://github.com/pamidur/aspect-injector
7>AspectInjector : error AI_FAIL: Aspect Injector processing has failed. See other errors.

Don't know even what to think.

**Comment by pamidur** [comment]
Hey @manson , thatnk you for the report and sorry for the delay. Would it be possible to share the code of the affected classs?

**Comment by praaline** [comment]
We had the same error when adding an attribute to a class that contained an async method that had not been implemented yet and for which the compiler was giving a warning. The method in question was:
`
public async Task NotYetImprlemented(int parameter)
{
    throw NotImplementedException();
}
`
which is the default body when asking visual studio to "implement" an interface. After I replaced the "throw..." statement (which is not asynchronous) with the statement "await Task.CompletedTask;", the compiler warnings went away and AspectInjector worked.

**Comment by pamidur** [comment]
Interesting find, it should be quite easy to check for. I'll try to have a
look shortly
