### ISSUE TITLE
[2.8.2][macOS] error AI_FAIL: Aspect Injector processing has failed

### ISSUE THREAD

**Issue by Alex-Dobrynin** [pamidur/aspect-injector#220]
After update to 2.8.2 from version 2.8.1 cannot build my netstandard2.1, getting error mentioned in title. In macOS
![image](https://github.com/pamidur/aspect-injector/assets/23138430/892c7b5f-02e4-4053-aa84-63f175286db8)

**Comment by pamidur** [comment]
Hi, thank you for the report!
Would you be able to submit the whole build log or at other least parts
related to Aspect Injectior?

**Comment by pamidur** [comment]
please let me know if 2.8.3-pre1 fixes it for you!

**Comment by Alex-Dobrynin** [comment]
the same

**Comment by kerojiang** [comment]
I got the same error on windows 
This is build log 
2>  AspectInjector|2.8.2: Found 0 aspects, 6 injections
2>AspectInjector|2.8.2 : error AI_ERR0: Processing failure: System.ArgumentException: Arg_ArgumentException
2>     at Mono.Cecil.Pdb.ISymUnmanagedWriter2.OpenScope(Int32 startOffset, Int32& pRetVal)
2>     at Mono.Cecil.Pdb.NativePdbWriter.DefineScope(ScopeDebugInformation scope, MethodDebugInformation info, MetadataToken& import_parent)
2>     at Mono.Cecil.Pdb.NativePdbWriter.DefineScope(ScopeDebugInformation scope, MethodDebugInformation info, MetadataToken& import_parent)
2>     at Mono.Cecil.Pdb.NativePdbWriter.Write(MethodDebugInformation info)
2>     at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
2>     at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
2>     at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
2>     at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
2>     at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
2>     at Mono.Cecil.MetadataBuilder.AddTypes()
2>     at Mono.Cecil.MetadataBuilder.BuildTypes()
2>     at Mono.Cecil.MetadataBuilder.BuildModule()
2>     at Mono.Cecil.MetadataBuilder.BuildMetadata()
2>     at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
2>     at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
2>     at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
2>     at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
2>     at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
2>     at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
2>     at Mono.Cecil.ModuleDefinition.Write(WriterParameters parameters)
2>     at Mono.Cecil.AssemblyDefinition.Write(WriterParameters parameters)
2>     at FluentIL.PatcherBase.WriteAssembly(AssemblyDefinition assembly, Boolean writeSymbols, Boolean verbose)
2>     at FluentIL.PatcherBase.Process(String assemblyFile, IAssemblyResolver resolver, Boolean optimize, Boolean verbose)
2>     at FluentIL.PatcherBase.Process(String assemblyFile, IReadOnlyList`1 references, Boolean optimize, Boolean verbose)
2>     at AspectInjector.Compiler.Execute(String filename, IReadOnlyList`1 references, Boolean optimize, Boolean verbose). Please submit an issue to https://github.com/pamidur/aspect-injector
2>AspectInjector : error AI_FAIL: Aspect Injector processing has failed. See other errors.

**Comment by DevRuWi** [comment]
> please let me know if 2.8.3-pre1 fixes it for you!

For me at least, 2.8.3-pre1 does not fix the problem but it seems to happen a lot less frequently. My call stack is different though:

13>AspectInjector|2.8.3 : error AI_ERR0: Processing failure: System.IO.IOException: IO_SharingViolation_File, C:\[myprojectpath]\obj\Debug\Wet.Modules.LetPlc24.dll
13>     at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String , FileMode , FileAccess , FileShare , FileOptions )
13>     at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
13>     at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
13>     at System.IO.Strategies.SyncWindowsFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
13>     at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
13>     at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream , String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
13>     at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
13>     at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions )
13>     at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , Boolean )
13>     at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare )
13>     at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
13>     at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
13>     at Mono.Cecil.BaseAssemblyResolver.SearchDirectory(AssemblyNameReference name, IEnumerable`1 directories, ReaderParameters parameters)
13>     at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
13>     at FluentIL.Resolvers.KnownReferencesAssemblyResolver.LookupAssembly(AssemblyNameReference name, ReaderParameters parameters)
13>     at FluentIL.Resolvers.CachedAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
13>     at FluentIL.PatcherBase.ReadAssembly(String assemblyFile, IAssemblyResolver resolver, Boolean readSymbols, Boolean verbose)
13>     at FluentIL.PatcherBase.Process(String assemblyFile, IAssemblyResolver resolver, Boolean optimize, Boolean verbose)
13>     at FluentIL.PatcherBase.Process(String assemblyFile, IReadOnlyList`1 references, Boolean optimize, Boolean verbose)
13>     at AspectInjector.Compiler.Execute(String filename, IReadOnlyList`1 references, Boolean optimize, Boolean verbose). Please submit an issue to https://github.com/pamidur/aspect-injector
13>AspectInjector : error AI_FAIL: Aspect Injector processing has failed. See other errors.

**Comment by real-zony** [comment]
The macOS 13.4 also had the same issue. The version of AspectInjector is 2.8.2. It works normally in the Docker container of X64. My MacBook is M2 Max and uses the ARM version of dotnet.

**Comment by real-zony** [comment]
My temporary solution is to use Docker (x86) debugging in Rider (through Rosetta 2), but this makes the debugging very slow each time. Is there any update on this issue? Thank you.

**Comment by pamidur** [comment]
Could you please use 2.8.1 while I'm fixing this?
Just to double check,
2.8.2 does not work for x86 and arm
and 2.8.1 does not work only for arm
Correct?

**Comment by dartasen** [comment]
Same issue

**Comment by pamidur** [comment]
@real-zony , @dartasen, @Alex-Dobrynin ,
Unfortunatelly I don't have arm based mac machine to test it , so I have to rely on you.
Could you please confirm that 2.8.1 works fine on _arm_ machine ?

**Comment by Alex-Dobrynin** [comment]
Yes, 2.8.1 it works on mac m1

**Comment by pamidur** [comment]
Hey guys, could you please try [2.8.3-pre2](https://github.com/pamidur/aspect-injector/releases/tag/2.8.3-pre2) ?

**Comment by dartasen** [comment]
> Hey guys, could you please try [2.8.3-pre2](https://github.com/pamidur/aspect-injector/releases/tag/2.8.3-pre2) ?

Same issue, unable to build 
![image](https://github.com/pamidur/aspect-injector/assets/10561268/c4245488-0e8b-43ec-ac32-26f0f15c3802)

**Comment by pamidur** [comment]
do you use Rosetta ?

**Comment by serfend** [comment]
when your method return is not `void`,you should only use `Kind.Around`
```csharp

		[Advice(Kind.Around, Targets = Target.Method)]
		public object OnEnter([Argument(Source.Name)] string name,
			[Argument(Source.Arguments)] object[] args,
			[Argument(Source.Type)] Type hostType,
			[Argument(Source.Target)] Func<object[], object> target,
			[Argument(Source.Triggers)] System.Attribute[] triggers)
		{
			var mutex = new Mutex(false, Name);
			mutex.WaitOne();
			var result = target(args);
			mutex.ReleaseMutex();
			return result;
		}
```

**Comment by serfend** [comment]
but while user use MVC , such error followed wont be shown.
```
AI_EA00	Advice 'OnEnter' must return 'object' for 'Around' advice	Test.Aspect-Injector.Failed	D:\backup\0.Main\workspace\resources\Test.Aspect-Injector.Failed\Test.Aspect-Injector.Failed\Test.Aspect-Injector.Failed\MutexHandlerAttribute.cs	43	活动

```

thats unexpected.

**Comment by serfend** [comment]
you can refer to [demo](https://github.com/serfend/Test.Aspect-Injector.Failed) for a success running.

**Comment by serfend** [comment]
amazing , i move exactly same code into other project , same error occurred.
windows11/vs2022 17.4.4.
```
AI_FAIL	Aspect Injector processing has failed. See other errors.	ProjectCommon	
..\Common\AspectInjector	1	
```

**Comment by serfend** [comment]
i think i found where problem is,see [docs](https://github.com/serfend/Test.Aspect-Injector.Failed/commit/1a58068cb2f267a62312a2f85c531d0ea9bed3ab)

**Comment by stilettk** [comment]
I'm experiencing the same issue, here is the detailed log:
```
     2>Target "_ASI_InjectAspectsCore" in file "/Users/stilettk/.nuget/packages/aspectinjector/2.8.3-pre2/buildTransitive/netstandard2.0/AspectInjector.targets" from project "/Users/stilettk/RiderProjects/loyalty/tests/Dodo.Loyalty.ComponentTests/Dodo.Loyalty.ComponentTests.csproj" (target "InjectAspects" depends on it):
       Set Property: _ProcessCmd="/Users/stilettk/.nuget/packages/aspectinjector/2.8.3-pre2/buildTransitive/netstandard2.0/../../build/_bin/osx-arm64/AspectInjector" -rf "/Users/stilettk/RiderProjects/loyalty/tests/Dodo.Loyalty.ComponentTests/obj/Debug/net7.0/Dodo.Loyalty.ComponentTests.dll._asi_refs" "/Users/stilettk/RiderProjects/loyalty/tests/Dodo.Loyalty.ComponentTests/obj/Debug/net7.0/Dodo.Loyalty.ComponentTests.dll"
       Task "Message" skipped, due to false condition; ( '$(AspectInjector_Debug)' == 'true' ) was evaluated as ( 'false' == 'true' ).
       Using "Exec" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
       Task "Exec"
         Task Parameter:Command="/Users/stilettk/.nuget/packages/aspectinjector/2.8.3-pre2/buildTransitive/netstandard2.0/../../build/_bin/osx-arm64/AspectInjector" -rf "/Users/stilettk/RiderProjects/loyalty/tests/Dodo.Loyalty.ComponentTests/obj/Debug/net7.0/Dodo.Loyalty.ComponentTests.dll._asi_refs" "/Users/stilettk/RiderProjects/loyalty/tests/Dodo.Loyalty.ComponentTests/obj/Debug/net7.0/Dodo.Loyalty.ComponentTests.dll"
         Task Parameter:EchoOff=True
         Task Parameter:IgnoreExitCode=True
         Task Parameter:WorkingDirectory=/Users/stilettk/.nuget/packages/aspectinjector/2.8.3-pre2/buildTransitive/netstandard2.0/
         /var/folders/y5/bg13rk8164n771x2jq7892ph0000gn/T/MSBuildTempstilettk/tmpaa7b21c171eb4634b4ae0d25bde46562.exec.cmd: line 2: 29017 Killed: 9               "/Users/stilettk/.nuget/packages/aspectinjector/2.8.3-pre2/buildTransitive/netstandard2.0/../../build/_bin/osx-arm64/AspectInjector" -rf "/Users/stilettk/RiderProjects/loyalty/tests/Dodo.Loyalty.ComponentTests/obj/Debug/net7.0/Dodo.Loyalty.ComponentTests.dll._asi_refs" "/Users/stilettk/RiderProjects/loyalty/tests/Dodo.Loyalty.ComponentTests/obj/Debug/net7.0/Dodo.Loyalty.ComponentTests.dll"
         Output Property: _AspectExitCode=137
       Done executing task "Exec".
       Using "Error" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
       Task "Error"
         Task Parameter:File=AspectInjector
         Task Parameter:Text=Aspect Injector processing has failed. See other errors.
         Task Parameter:Code=AI_FAIL
     2>AspectInjector : error AI_FAIL: Aspect Injector processing has failed. See other errors. [/Users/stilettk/RiderProjects/loyalty/tests/Dodo.Loyalty.ComponentTests/Dodo.Loyalty.ComponentTests.csproj]
       Done executing task "Error" -- FAILED.
     2>Done building target "_ASI_InjectAspectsCore" in project "Dodo.Loyalty.ComponentTests.csproj" -- FAILED.
```

**Comment by pamidur** [comment]
I'm really sorry my Mac users, since I  don't have it is hard to figure out what actually goes wrong.
@stilettk do you have Rosetta installed?

**Comment by stilettk** [comment]
> @stilettk do you have Rosetta installed?

I didn't explicitly install it, but according to [this](https://apple.stackexchange.com/a/441395), I have it installed.

**Comment by stilettk** [comment]
@pamidur FYI in 2.8.3-pre3 the problem persists
<details>
  <summary>Build log</summary>
```
     2>Target "_ASI_InjectAspectsCore" in file "/Users/stilettk/.nuget/packages/aspectinjector/2.8.3-pre3/buildTransitive/netstandard2.0/AspectInjector.targets" from project "/Users/stilettk/RiderProjects/loyalty/tests/Dodo.Loyalty.ComponentTests/Dodo.Loyalty.ComponentTests.csproj" (target "InjectAspects" depends on it):
       Set Property: _ProcessCmd="/Users/stilettk/.nuget/packages/aspectinjector/2.8.3-pre3/buildTransitive/netstandard2.0/../../build/_bin/osx-arm64/AspectInjector" -rf "/Users/stilettk/RiderProjects/loyalty/tests/Dodo.Loyalty.ComponentTests/obj/Debug/net7.0/Dodo.Loyalty.ComponentTests.dll._asi_refs" "/Users/stilettk/RiderProjects/loyalty/tests/Dodo.Loyalty.ComponentTests/obj/Debug/net7.0/Dodo.Loyalty.ComponentTests.dll"
       Task "Message" skipped, due to false condition; ( '$(AspectInjector_Debug)' == 'true' ) was evaluated as ( 'false' == 'true' ).
       Using "Exec" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
       Task "Exec"
         Task Parameter:WorkingDirectory=/Users/stilettk/.nuget/packages/aspectinjector/2.8.3-pre3/buildTransitive/netstandard2.0/
         Task Parameter:Command="/Users/stilettk/.nuget/packages/aspectinjector/2.8.3-pre3/buildTransitive/netstandard2.0/../../build/_bin/osx-arm64/AspectInjector" -rf "/Users/stilettk/RiderProjects/loyalty/tests/Dodo.Loyalty.ComponentTests/obj/Debug/net7.0/Dodo.Loyalty.ComponentTests.dll._asi_refs" "/Users/stilettk/RiderProjects/loyalty/tests/Dodo.Loyalty.ComponentTests/obj/Debug/net7.0/Dodo.Loyalty.ComponentTests.dll"
         Task Parameter:IgnoreExitCode=True
         Task Parameter:EchoOff=True
         /var/folders/y5/bg13rk8164n771x2jq7892ph0000gn/T/MSBuildTempstilettk/tmp3c20c11a47674faaaeb388be23585be7.exec.cmd: line 2: 35405 Killed: 9               "/Users/stilettk/.nuget/packages/aspectinjector/2.8.3-pre3/buildTransitive/netstandard2.0/../../build/_bin/osx-arm64/AspectInjector" -rf "/Users/stilettk/RiderProjects/loyalty/tests/Dodo.Loyalty.ComponentTests/obj/Debug/net7.0/Dodo.Loyalty.ComponentTests.dll._asi_refs" "/Users/stilettk/RiderProjects/loyalty/tests/Dodo.Loyalty.ComponentTests/obj/Debug/net7.0/Dodo.Loyalty.ComponentTests.dll"
         Output Property: _AspectExitCode=137
       Done executing task "Exec".
       Using "Error" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
       Task "Error"
         Task Parameter:File=AspectInjector
         Task Parameter:Code=AI_FAIL
         Task Parameter:Text=Aspect Injector processing has failed. See other errors.
     2>AspectInjector : error AI_FAIL: Aspect Injector processing has failed. See other errors. [/Users/stilettk/RiderProjects/loyalty/tests/Dodo.Loyalty.ComponentTests/Dodo.Loyalty.ComponentTests.csproj]
       Done executing task "Error" -- FAILED.
     2>Done building target "_ASI_InjectAspectsCore" in project "Dodo.Loyalty.ComponentTests.csproj" -- FAILED.
```
</details>

**Comment by pamidur** [comment]
can you try https://www.nuget.org/packages/AspectInjector/2.8.3-pre3#supportedframeworks-body-tab ? and see if it helps
if it still does not work, you can try adding 
```xml
<PropertyGroup>
    <AspectInjector_UseRosetta>true</AspectInjector_UseRosetta>
  </PropertyGroup>
```

**Comment by stilettk** [comment]
What do you mean by trying https://www.nuget.org/packages/AspectInjector/2.8.3-pre3#supportedframeworks-body-tab? To use `net20` or `netstandard2.0`? Unfortunately, I can't do this in my project because all references require newer versions.

`AspectInjector_UseRosetta` helper though. But I hope that this won't be a requirement because AspectInjector is a transitive dependency for us (from Allure.NUnit).

**Comment by pamidur** [comment]
it is there just to test it. It seems like Rosetta is going to be a requirement and after the next release it is going to be the only supported option. I just can't make it run on apple silicon without rosetta without having actual mac :(

**Comment by gshuchi** [comment]
Hey People! Install the terminal with Rosetta settings and this error will be gone after ``dotnet build`` command.

**Comment by Austin1** [comment]
I'm here with this same issue and can't seem to figure it out. I'm not much of a developer but working to build another application. I had ChatGPT write me a very simple program to try building just for AspectInjector. 

here is my csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspectInjector_UseRosetta>true</AspectInjector_UseRosetta>
  </PropertyGroup>
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Message Text="$(PATH)" Importance="high" />
  </Target>
  <ItemGroup>
    <PackageReference Include="AspectInjector" Version="2.8.2" />
  </ItemGroup>
</Project>
```
here is my Program.cs:
```
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
```

Attaching "dotnet build" log from M2 Macbook Air using VSCode with C# Dev Kit. - See Line 52,881:
[build-log.txt](https://github.com/user-attachments/files/17952591/build-log.txt)

**Comment by pkirilin** [comment]
I just faced the same issue on Mac M4. The error is gone after I installed Rosetta using the following command in terminal:

```shell
softwareupdate --install-rosetta
```

**Comment by topharley** [comment]
On Mac M4 helped to:
1. restore and use 2.8.3-pre3 version package
2. sign it: codesign -s - /Users/you_username/.nuget/packages/aspectinjector/2.8.3-pre3/build/_bin/osx-arm64/AspectInjector
3. add as reference with version in Directory.Packages.props
<PackageVersion Include="AspectInjector" Version="2.8.3-pre3"/>
4. reference in csproj
<PackageReference Include="AspectInjector"/>

**Comment by PeterSoder** [comment]
For us every version after 2.7.2 give this error, which sound very similar to the Mac problems.
On Win11 (Ryzen processor if that makes any difference.)
Sorry if I should post this as a separate issue.

`5>AspectInjector|2.7.4: Found 1 aspects, 190 injections
5>AspectInjector|2.7.4 : error AI_ERR0: Processing failure: System.InvalidOperationException: Expected sequence is not found even once. Unsupported language/version ?
5>   at FluentIL.MethodEditor.OnEveryOccasionOf(MethodBody body, Func``2 predicate, PointCut pc, Instruction startingFrom)
5>   at FluentIL.MethodEditor.OnCall(MethodBody body, MethodReference method, PointCut pc, Instruction startingFrom)
5>   at AspectInjector.Core.Advice.Weavers.Processes.AfterAsyncWeaveProcess.FindOrCreateAfterStateMachineMethod()
5>   at AspectInjector.Core.Advice.Weavers.Processes.AfterStateMachineWeaveProcessBase.Execute()
5>   at AspectInjector.Core.Advice.Weavers.AdviceStateMachineWeaver.WeaveMethod(MethodDefinition method, InjectionDefinition injection)
5>   at AspectInjector.Core.Advice.Weavers.AdviceInlineWeaver.Weave(InjectionDefinition injection)
5>   at AspectInjector.Core.Processor.PatchAssembly(AssemblyDefinition assembly, Boolean optimize, Boolean verbose)
5>   at FluentIL.PatcherBase.Process(String assemblyFile, IAssemblyResolver resolver, Boolean optimize, Boolean verbose)
5>   at FluentIL.PatcherBase.Process(String assemblyFile, IReadOnlyList``1 references, Boolean optimize, Boolean verbose)
5>   at AspectInjector.Compiler.Execute(String filename, IReadOnlyList``1 references, Boolean optimize, Boolean verbose). Please submit an issue to https://github.com/pamidur/aspect-injector
5>AspectInjector : error AI_FAIL: Aspect Injector processing has failed. See other errors.`

**Comment by MardorZ** [comment]
Late to the party, but 2.9.0 works perfectly on MAC M4, thanks!
