### ISSUE TITLE
Failed to resolve assembly: 'mscorlib, Version=4.0.0.0

### ISSUE THREAD

**Issue by chixinzei** [pamidur/aspect-injector#227]
**Environment (please complete the following information):**
 - OS: [e.g. windows, linux, macos]
 - Framework: [e.g. net461, netcoreapp3.1, net6.0]
 - Type of application: [e.g. console, webapp, winforms, wpf, xamarin, mobile etc]
 - Version of AspectInjector: [e.g. 2.7.1]

**Describe the bug**
A clear and concise description of what the bug is. An what is expected behavior.

**To Reproduce**
A steps to reproduce the bug. Or a description when it happens (in compile-time, in runtime).

**Additional context**
Add any other context about the problem here. Please add stack trace here. Please put it under spoiler if possible.

**Comment by chixinzei** [comment]
sorry ,there is right question

Environment (please complete the following information):

OS: windows 10
Framework: VB. net 4.6.1, 
Type of application:  winforms
Version of AspectInjector: [e.g. 2.7.1]
Describe the bug

1>AspectInjector|2.8.1 : error AI_ERR0: Processing failure: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
1>     at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
1>     at FluentIL.Resolvers.KnownReferencesAssemblyResolver.LookupAssembly(AssemblyNameReference name, ReaderParameters parameters)
1>     at FluentIL.Resolvers.CachedAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
1>     at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name)
1>     at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
1>     at Mono.Cecil.ModuleDefinition.Resolve(TypeReference type)
1>     at Mono.Cecil.TypeReference.Resolve()
1>     at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
1>     at Mono.Cecil.SignatureReader.ReadCustomAttributeEnum(TypeReference enum_type)
1>     at Mono.Cecil.SignatureReader.ReadCustomAttributeElementValue(TypeReference type)
1>     at Mono.Cecil.SignatureReader.ReadCustomAttributeElement(TypeReference type)
1>     at Mono.Cecil.SignatureReader.ReadCustomAttributeConstructorArguments(CustomAttribute attribute, Collection`1 parameters)
1>     at Mono.Cecil.MetadataReader.ReadCustomAttributeSignature(CustomAttribute attribute)
1>     at Mono.Cecil.CustomAttribute.<Resolve>b__35_0(CustomAttribute attribute, MetadataReader reader)
1>     at Mono.Cecil.ModuleDefinition.Read[TItem](TItem item, Action`2 read)
1>     at Mono.Cecil.CustomAttribute.Resolve()
1>     at Mono.Cecil.CustomAttribute.get_ConstructorArguments()
1>     at Mono.Cecil.ImmediateModuleReader.ReadCustomAttributes(ICustomAttributeProvider provider)
1>     at Mono.Cecil.ImmediateModuleReader.ReadFields(TypeDefinition type)
1>     at Mono.Cecil.ImmediateModuleReader.ReadType(TypeDefinition type)
1>     at Mono.Cecil.ImmediateModuleReader.ReadTypes(Collection`1 types)
1>     at Mono.Cecil.ImmediateModuleReader.ReadModule(ModuleDefinition module, Boolean resolve_attributes)
1>     at Mono.Cecil.ImmediateModuleReader.<ReadModule>b__2_0(ModuleDefinition module, MetadataReader reader)
1>     at Mono.Cecil.ModuleDefinition.Read[TItem](TItem item, Action`2 read)
1>     at Mono.Cecil.ImmediateModuleReader.ReadModule()
1>     at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
1>     at Mono.Cecil.ModuleDefinition.ReadModule(Disposable`1 stream, String fileName, ReaderParameters parameters)
1>     at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
1>     at Mono.Cecil.BaseAssemblyResolver.SearchDirectory(AssemblyNameReference name, IEnumerable`1 directories, ReaderParameters parameters)
1>     at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
1>     at FluentIL.Resolvers.KnownReferencesAssemblyResolver.LookupAssembly(AssemblyNameReference name, ReaderParameters parameters)
1>     at FluentIL.Resolvers.CachedAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
1>     at FluentIL.PatcherBase.ReadAssembly(String assemblyFile, IAssemblyResolver resolver, Boolean readSymbols, Boolean verbose)
1>     at FluentIL.PatcherBase.Process(String assemblyFile, IAssemblyResolver resolver, Boolean optimize, Boolean verbose)
1>     at FluentIL.PatcherBase.Process(String assemblyFile, IReadOnlyList`1 references, Boolean optimize, Boolean verbose)
1>     at AspectInjector.Compiler.Execute(String filename, IReadOnlyList`1 references, Boolean optimize, Boolean verbose). Please submit an issue to https://github.com/pamidur/aspect-injector
1>AspectInjector : error AI_FAIL: Aspect Injector processing has failed. See other errors.

To Reproduce
The above error occurred when I compiled the current project after I added an AspectInjector reference using nuget,pls help ,thank you very much !

Additional context
nothing

**Comment by pamidur** [comment]
Hey, thank you for the report. Could you please try and see if the issue is still there in https://github.com/pamidur/aspect-injector/releases/tag/2.9.0-pre1 ? There were some significant changes
