### ISSUE TITLE
Encountering "error AI_FAIL: Aspect Injector processing has failed. See other errors." with latest Logging .NET nuget package

### ISSUE THREAD

**Issue by AdithyaAthreya** [pamidur/aspect-injector#237]
**Environment (please complete the following information):**
 - OS: Windows
 - Framework: net8.0
 - Type of application: AWS lambda project
 - Version of AspectInjector: 2.8.1, 2.8.2
 - Logging library version: 1.6.0, 1.6.1

**Describe the bug**
The Logging nuget is throwing the below exception at compile time when a .net 8.0 lambda project is being compiled.

AspectInjector|2.8.1: Found 0 aspects, 14 injections
3>AspectInjector|2.8.1 : error AI_ERR0: Processing failure: System.InvalidOperationException: Expected sequence is not found even once. Unsupported language/version ?
3>   at FluentIL.MethodEditor.OnEveryOccasionOf(MethodBody body, Func`2 predicate, PointCut pc, Instruction startingFrom)
3>   at FluentIL.MethodEditor.OnCall(MethodBody body, MethodReference method, PointCut pc, Instruction startingFrom)
3>   at AspectInjector.Core.Advice.Weavers.Processes.AfterAsyncWeaveProcess.FindOrCreateAfterStateMachineMethod()
3>   at AspectInjector.Core.Advice.Weavers.Processes.AfterStateMachineWeaveProcessBase.Execute()
3>   at AspectInjector.Core.Advice.Weavers.AdviceStateMachineWeaver.WeaveMethod(MethodDefinition method, InjectionDefinition injection)
3>   at AspectInjector.Core.Advice.Weavers.AdviceInlineWeaver.Weave(InjectionDefinition injection)
3>   at AspectInjector.Core.Processor.PatchAssembly(AssemblyDefinition assembly, Boolean optimize, Boolean verbose)
3>   at FluentIL.PatcherBase.Process(String assemblyFile, IAssemblyResolver resolver, Boolean optimize, Boolean verbose)
3>   at FluentIL.PatcherBase.Process(String assemblyFile, IReadOnlyList`1 references, Boolean optimize, Boolean verbose)
3>   at AspectInjector.Compiler.Execute(String filename, IReadOnlyList`1 references, Boolean optimize, Boolean verbose). Please submit an issue to https://github.com/pamidur/aspect-injector
3>AspectInjector : error AI_FAIL: Aspect Injector processing has failed. See other errors.

**To Reproduce**
A steps to reproduce the bug. Or a description when it happens (in compile-time, in runtime).

**Additional context**
I upgraded the AspectInjector nuget to 2.8.2 but it did not resolve the issue. Only upon downgrading the Logging nuget to 1.5.1 did the issue go away and I was able to get a successful build.

**Comment by Austin1** [comment]
I'm here with same issue on MacOS

    /var/folders/5s/gdk6tvb518j18bjr7spjjctr0000gn/T/MSBuildTempaustin/tmpd5408649ab8547c8aa3dce8c9695d162.exec.cmd: line 2: 21818 Killed: 9               "/Users/austin/.nuget/packages/aspectinjector/2.8.2/buildTransitive/netstandard2.0/../../build/_bin/osx-arm64/AspectInjector" -rf "/Users/austin/Documents/GitHub/TestAspect/TestAspectInjector/obj/Debug/net9.0/TestAspectInjector.dll._asi_refs" "/Users/austin/Documents/GitHub/TestAspect/TestAspectInjector/obj/Debug/net9.0/TestAspectInjector.dll"

**Comment by pamidur** [comment]
Hey, thank you for the report. Could you please try and see if the issue is still there in https://github.com/pamidur/aspect-injector/releases/tag/2.9.0-pre1 ? There were some significant changes
