### ISSUE TITLE
Error when ctor call : this()

### ISSUE THREAD

**Issue by lcrescenzo** [pamidur/aspect-injector#38]
Exception error:

Exception: Cannot find base class ctor call
   at AspectInjector.BuildTask.Extensions.MemberExtensions.FindBaseClassCtorCall(MethodDefinition md)
   at AspectInjector.BuildTask.Contexts.TargetMethodContext.SetupEntryPoints()
   at AspectInjector.BuildTask.Contexts.TargetMethodContext..ctor(MethodDefinition targetMethod)
   at AspectInjector.BuildTask.Contexts.MethodContextFactory.GetOrCreateContext(MethodDefinition md)
   at AspectInjector.BuildTask.Contexts.TypeContextFactory.<GetOrCreateContext>b__2(MethodDefinition c)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AspectInjector.BuildTask.Contexts.TypeContextFactory.GetOrCreateContext(TypeDefinition td)
   at AspectInjector.BuildTask.Processors.ModuleProcessors.InjectionProcessor.<>c__DisplayClass12.<ProcessAspectDefinitions>b__f(AspectDefinition def)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AspectInjector.BuildTask.Processors.ModuleProcessors.InjectionProcessor.ProcessAspectDefinitions(MethodDefinition targetMethod, String targetName, IEnumerable`1 aspectDefinitions)
   at AspectInjector.BuildTask.Processors.ModuleProcessors.InjectionProcessor.ProcessModule(ModuleDefinition module)
   at AspectInjector.BuildTask.Processors.AssemblyProcessor.Process(AssemblyDefinition assembly)
   at AspectInjector.BuildTask.AspectInjectorBuildTask.Execute()

Class to getenerate error: 
 public class Runner
 {
        public Runner() : **this**(0)
        {
        }
        public Runner(int a)
        {
        }

        [Aspect(typeof(Trace))]
        public void Method()
        {
        }
}

**Comment by om2804** [comment]
Hmm. The author had disappeared?
Bugfix in https://github.com/pamidur/aspect-injector/pull/39

**Comment by pamidur** [comment]
I'm not :)

**Comment by pamidur** [comment]
fixed in b6dc9bed2580a983c0abd088e571b16c9e693bf1

**Comment by om2804** [comment]
Nice! 
I wait Nuget-packet :)

**Comment by lcrescenzo** [comment]
nice tks

This component works with Mef?

**Comment by pamidur** [comment]
I suppose it does. Need to check. You could either build project on your own or wait for nuget package beta-2 (only one bug left for beta-2) :)
