### ISSUE TITLE
Error at cleaning up references to the Broker assembly

### ISSUE THREAD

**Issue by YuriyIvon** [pamidur/aspect-injector#5]
InvalidCastException: Unable to cast object of type 'Mono.Cecil.GenericInstanceMethod' to type 'Mono.Cecil.TypeReference'.
at AspectInjector.BuildTask.Processors.ModuleProcessors.Janitor.IsInstructionReferencesBroker(Instruction instruction)
at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
at AspectInjector.BuildTask.Processors.ModuleProcessors.Janitor.IsMethodBodyReferencesBroker(MethodBody methodBody)
at AspectInjector.BuildTask.Processors.ModuleProcessors.Janitor.CheckMethodReferencesBroker(MethodDefinition method)
at System.Collections.Generic.List`1.ForEach(Action`1 action)
at AspectInjector.BuildTask.Processors.ModuleProcessors.Janitor.CheckTypeReferencesBroker(TypeDefinition type)
at System.Collections.Generic.List`1.ForEach(Action`1 action)
at AspectInjector.BuildTask.Processors.ModuleProcessors.Janitor.ProcessModule(ModuleDefinition module)
at AspectInjector.BuildTask.Processors.AssemblyProcessor.Process(AssemblyDefinition assembly)
at AspectInjector.BuildTask.AspectInjectorBuildTask.Execute()

**Comment by YuriyIvon** [comment]
Fixed in 0.9.1
