### ISSUE TITLE
Correctly support generator methods (yield return) as a target

### ISSUE THREAD

**Issue by YuriyIvon** [pamidur/aspect-injector#6]

**Comment by pamidur** [comment]
How we can support it? We can't guarantee that "After" would ever get executed. It IS ok in terms of c# standards. Is it ok in terms of AOP?

**Comment by pamidur** [comment]
Implementation: find all ret in MoveNext() the if false - execute aspects

**Comment by pamidur** [comment]
done in https://github.com/pamidur/aspect-injector/releases/tag/1.0.0-rc1

**Comment by lezar44** [comment]
Hello,
I'm having an issue with v2.8.2 of aspect injector when my code has yield return instruction.
There is a compiling error : 
_AspectInjector|2.8.2 : error AI_ERR0: Processing failure: System.InvalidOperationException: Expected sequence is not found even once. Unsupported language/version ?
   at FluentIL.MethodEditor.OnEveryOccasionOf(MethodBody body, Func`2 predicate, PointCut pc, Instruction startingFrom)
   at AspectInjector.Core.Advice.Weavers.Processes.AfterIteratorWeaveProcess.FindOrCreateAfterStateMachineMethod()
   at AspectInjector.Core.Advice.Weavers.Processes.AfterStateMachineWeaveProcessBase.Execute()
   at AspectInjector.Core.Advice.Weavers.AdviceStateMachineWeaver.WeaveMethod(MethodDefinition method, InjectionDefinition injection)
   at AspectInjector.Core.Advice.Weavers.AdviceInlineWeaver.Weave(InjectionDefinition injection)
   at AspectInjector.Core.Processor.PatchAssembly(AssemblyDefinition assembly, Boolean optimize, Boolean verbose)
   at FluentIL.PatcherBase.Process(String assemblyFile, IAssemblyResolver resolver, Boolean optimize, Boolean verbose)
   at FluentIL.PatcherBase.Process(String assemblyFile, IReadOnlyList`1 references, Boolean optimize, Boolean verbose)
   at AspectInjector.Compiler.Execute(String filename, IReadOnlyList`1 references, Boolean optimize, Boolean verbose). Please submit an issue to https://github.com/pamidur/aspect-injector
AspectInjector : error AI_FAIL: Aspect Injector processing has failed. See other errors._

I don't know if it can be corrected as in version 1.0.0 RC1

Thank you for any help.
