### ISSUE TITLE
[BUG] Compilation Error if use Aspect from another Portable Library .dll

### ISSUE THREAD

**Issue by xandraele** [pamidur/aspect-injector#7]
Steps to reproduce:
1. Create portable .dll
2. Move TraceAspect there.
3. Create Console App. with TestClass
4. Link portable .dll to Console App
5. Mark TestClass with attribute [Aspect(typeof(TraceAspect))]
6. Try to compile.

Error	2	InvalidCastException: Unable to cast object of type 'Mono.Cecil.TypeReference' to type 'Mono.Cecil.TypeDefinition'.
   at AspectInjector.BuildTask.Processors.ModuleProcessors.InjectionProcessor.<>c__DisplayClassd.<ProcessAspectAttributes>b__a(CustomAttribute attr)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AspectInjector.BuildTask.Processors.ModuleProcessors.InjectionProcessor.ProcessAspectAttributes(MethodDefinition targetMethod, String targetName, IEnumerable`1 aspectAttributes)
   at AspectInjector.BuildTask.Processors.ModuleProcessors.InjectionProcessor.ProcessModule(ModuleDefinition module)
   at AspectInjector.BuildTask.Processors.AssemblyProcessor.Process(AssemblyDefinition assembly)
   at AspectInjector.BuildTask.AspectInjectorBuildTask.Execute()
	ConsoleApplication2

**Comment by pamidur** [comment]
Thank you for the report.

**Comment by pamidur** [comment]
Fixed in 0.9.2 https://github.com/pamidur/aspect-injector/releases/tag/0.9.2

**Comment by xandraele** [comment]
Thanks. It was really quick. Good job!
