### ISSUE TITLE
[BUG] There is NullReferenceException if use Aspect with generic types

### ISSUE THREAD

**Issue by xandraele** [pamidur/aspect-injector#8]
Steps to reproduce:
1. Create portable library .dll and TraceAspect within
2. Create 4.5 framework .dll with generic class TestClass<T>
3. Use [Aspect(typeof(TraceAspect))] for TestClass<T>

Error	1	NullReferenceException: Object reference not set to an instance of an object.
   at AspectInjector.BuildTask.Extensions.TypeExtensions.IsTypeOf(TypeReference typeReference1, TypeReference typeReference2)
   at AspectInjector.BuildTask.Extensions.TypeExtensions.IsTypeOf(TypeReference typeReference, Type type)
   at AspectInjector.BuildTask.Contexts.TargetMethodContext.SetupSingleReturnPoint(Instruction suggestedSingleReturnPoint)
   at AspectInjector.BuildTask.Contexts.TargetMethodContext.SetupReturnPoints()
   at AspectInjector.BuildTask.Contexts.TargetMethodContext..ctor(MethodDefinition targetMethod)
   at AspectInjector.BuildTask.Contexts.MethodContextFactory.GetOrCreateContext(MethodDefinition md)
   at AspectInjector.BuildTask.Processors.ModuleProcessors.InjectionProcessor.ProcessAspectAttributes(MethodDefinition targetMethod, String targetName, IEnumerable`1 aspectAttributes)
   at AspectInjector.BuildTask.Processors.ModuleProcessors.InjectionProcessor.ProcessModule(ModuleDefinition module)
   at AspectInjector.BuildTask.Processors.AssemblyProcessor.Process(AssemblyDefinition assembly)
   at AspectInjector.BuildTask.AspectInjectorBuildTask.Execute()
	ITWORK.Solutions.FishingForecast.WebServices

**Comment by pamidur** [comment]
Thank you xandraele!
Fixed in 0.9.21, https://github.com/pamidur/aspect-injector/releases/tag/0.9.21
