### ISSUE TITLE
FileNotFoundException for AspectCodeFixProvider and MixinCodeFixProvider

### ISSUE THREAD

**Issue by ocherniavskyi** [pamidur/aspect-injector#81]
Plugins crushes time to time 

![image](https://user-images.githubusercontent.com/45246546/50637707-c3a41480-0f63-11e9-8d8b-85b1d2eacbb3.png)

StackTrace: System.IO.FileNotFoundException : Could not load file or assembly 'AspectInjector.Rules, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at AspectInjector.Analyzer.CodeFixes.AspectCodeFixProvider.get_FixableDiagnosticIds()
   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetAndTestFixableDiagnosticIds(CodeFixProvider codeFixProvider)
   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.<>c.<GetFixableDiagnosticIds>b__25_2(CodeFixProvider f)
   at System.Collections.Immutable.ImmutableInterlocked.GetOrAdd[TKey,TValue](ImmutableDictionary`2& location,TKey key,Func`2 valueFactory)
   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.<>c__DisplayClass25_0.<GetFixableDiagnosticIds>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunction[T](IExtensionManager extensionManager,Object extension,Func`1 function,T defaultValue)

**Comment by pamidur** [comment]
I guess I fixed it in 2.0.2, please check

**Comment by ocherniavskyi** [comment]
Now there is no crushes during "Project load -> build -> run", will see how its works during day to day work
