### ISSUE TITLE
error AI_ERR0: Processing failure: System.Exception: Cannot resolve generic parameter

### ISSUE THREAD

**Issue by LaborJos** [pamidur/aspect-injector#97]
**Exception Message**
```
29>  AspectInjector: Found 0 aspects, 262 injections
29>AspectInjector : error AI_ERR0: Processing failure: System.Exception: Cannot resolve generic parameter
29>     at FluentIL.Extensions.GenericProcessingExtension.ResolveGenericType(MemberReference member, TypeReference param)
29>     at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
29>     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
29>     at FluentIL.Extensions.GenericProcessingExtension.ParametrizeGenericInstance(MemberReference member, GenericInstanceType generic)
29>     at FluentIL.Extensions.GenericProcessingExtension.MakeCallReference(MemberReference member, FieldReference reference)
29>     at FluentIL.TypeMembers.Load(Cut cut, FieldReference field)
29>     at AspectInjector.Core.Extensions.FluentExtensions.LoadAspect(Cut cut, AspectDefinition aspect, MethodDefinition method, PointCut accessor)
29>     at AspectInjector.Core.Extensions.FluentExtensions.LoadAspect(Cut cut, AspectDefinition aspect)
29>     at AspectInjector.Core.Advice.Weavers.Processes.AdviceAroundProcess.<Execute>b__5_0(Cut e)
29>     at FluentIL.Cut.Here(PointCut pc)
29>     at FluentIL.MethodEditor.Instead(MethodBody body, PointCut action)
29>     at AspectInjector.Core.Processor.PatchAssembly(AssemblyDefinition assembly, Boolean optimize, Boolean verbose)
29>     at FluentIL.PatcherBase.Process(String assemblyFile, IAssemblyResolver resolver, Boolean optimize, Boolean verbose)
29>     at AspectInjector.Compiler.Execute(String filename, IReadOnlyList`1 references, Boolean optimize, Boolean verbose). Please submit an issue to https://github.com/pamidur/aspect-injector
29>AspectInjector : error AI_FAIL: Aspect Injector processing has failed. See other errors.
```

**Code**
```
namespace VM.ViewModels.Base
{
    using VM.Managed;
    using VM.ViewModels.Attributes;
    using VM.ViewModels.Pre;

    public class VariableViewModel : ExpressionViewModel<Variable>
    {
        public VariableViewModel(Identifier id, IDocumentViewModel parentDocument)
            : base(id, parentDocument)
        {
        }

        [AspectAttribute(nameof(Source))]
        public double Value { get; set; }
    }
}
```

Generic parameters are not used. However, the above error occurs.

**Comment by pamidur** [comment]
Hi,
Wow, this is new generic-related bug. I thought they were fixed long ago.
Thanks for the report. I'll be looking at it soon.

**Comment by LaborJos** [comment]
> Hi,
> Wow, this is new generic-related bug. I thought they were fixed long ago.
> Thanks for the report. I'll be looking at it soon.
@pamidur 
I have confirmed that no errors occur in VS 2019.

**Comment by pamidur** [comment]
Thank you for checking. I'm going to look into this bug as soon I return from vacation. Sorry for the delay.

**Comment by oleksandr-hulyi-sph** [comment]
Hey @LaborJos , I'm still working on it. The is much deeper than I thought so it takes time. Until then the simple workaround would be to use Scope.Global for your aspects

**Comment by pamidur** [comment]
I'm still working on it at this bug seem to be deeper than I thought. So it take time to fix it. Until then the workaround would be to used Scope.Global for your aspects

**Comment by pamidur** [comment]
Blocked by https://github.com/jbevain/cecil/issues/639

**Comment by pamidur** [comment]
Fixed in https://github.com/pamidur/aspect-injector/releases/tag/2.2.7
@ColmBhandal  you should be able to use Scope PerInstance now
Sorry for such a long delay, the issue drills down to how (not obvious) mono.cecil works sometimes.

**Comment by ColmBhandal** [comment]
Thanks!
